#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx --no -- commitlint --edit ""

# pnpm lint-staged

# pnpm exec tsc at each project
# curPath="./apps"
# for dir in ${curPath};do
#      if [ -d ${dir} ];then
#         cd ${dir}
#         pnpm exec tsc
#      fi
# done

