#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm lint-staged

npx secretlint "**/*"

# pnpm exec tsc at each project
curPath="./apps"
for dir in ${curPath};do
     if [ -d ${dir} ];then
        cd ${dir}
        pnpm exec tsc
     fi
done

